apiVersion: v1
kind: Namespace
metadata:
  name: telegram
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram
  namespace: telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram
  template:
    metadata:
      labels:
        app: telegram
    spec:
      containers:
        - name: telegram
          image: marceloaba/telegram:v1.0
          ports:
            - containerPort: 5001
          env:
            - name: TZ
              value: "America/Toronto"
            - name: FLASK_PORT
              value: "5001"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: TELEGRAM_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: TELEGRAM_CHAT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: telegram
  namespace: telegram
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
  selector:
    app: telegram
